export const AUTH_START="AUTH_START"
export const AUTH_SUCCESS="AUTH_SUCCESS"
export const AUTH_FAIL="AUTH_FAIL"
export const SET_USER_INFO="SET_USER_INFO"
export const AUTH_EXIT="AUTH_EXIT"

export const CHAT_LOADING="CHAT_LOADING"
export const CHAT_SUCCESS="CHAT_SUCCESS"
export const CHAT_FAIL="CHAT_FAIL"
export const DELETE_CHAT="DELETE_CHAT"
export const CLEAN_CHATS_DATA="CLEAN_CHATS_DATA"

export const SET_USER_CHATS_LIST="SET_USER_CHATS_LIST"
export const SET_SEARCH_CHATS_LIST="SET_SEARCH_CHATS_LIST"

export const APPEND_CHAT_MESSAGE="APPEND_CHAT_MESSAGE"
export const REMOVE_CHAT_MESSAGE="REMOVE_CHAT_MESSAGE"
export const SET_MESSAGE="SET_MESSAGE"